<a href="https://colab.research.google.com/github/sittidetw/dads5001_hiv_strategic_analysis/blob/main/09_Plotly/Week9_PK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Week9

Reference
- https://pbpython.com/plotly-look.html
- https://www.kaggle.com/crawford/80-cereals >> data set

In [1]:
import pandas as pd
import plotly.express as px

df = pd.read_csv('https://github.com/chris1610/pbpython/blob/master/data/cereal_data.csv?raw=True')
df.head()

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating,cereal
0,100% Bran,Nabisco,Cold,70,4,1,130,10.0,5.0,6,280,25,Top,1.0,0.33,68.40,1
1,100% Natural Bran,Quaker Oats,Cold,120,3,5,15,2.0,8.0,8,135,0,Top,1.0,1.00,33.98,1
2,All-Bran,Kellogs,Cold,70,4,1,260,9.0,7.0,5,320,25,Top,1.0,0.33,59.43,1
3,All-Bran with Extra Fiber,Kellogs,Cold,50,4,0,140,14.0,8.0,0,330,25,Top,1.0,0.50,93.70,1
4,Almond Delight,Ralston Purina,Cold,110,2,2,200,1.0,14.0,8,-1,25,Top,1.0,0.75,34.38,1

In [2]:
df.shape

(77, 17)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 17 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      77 non-null     object
 1   mfr       77 non-null     object
 2   type      77 non-null     object
 3   calories  77 non-null     int64
 4   protein   77 non-null     int64
 5   fat       77 non-null     int64
 6   sodium    77 non-null     int64
 7   fiber     77 non-null     float64
 8   carbo     77 non-null     float64
 9   sugars    77 non-null     int64
 10  potass    77 non-null     int64
 11  vitamins  77 non-null     int64
 12  shelf     77 non-null     object
 13  weight    77 non-null     float64
 14  cups      77 non-null     float64
 15  rating    77 non-null     float64
 16  cereal    77 non-null     int64
dtypes: float64(5), int64(8), object(4)
memory usage: 10.4+ KB

In [4]:
print(df['shelf'].unique())
print(df['type'].unique())
print(df['mfr'].unique(),  "  ,  ", df['mfr'].nunique())

['Top' 'Bottom' 'Middle']
['Cold' 'Hot']
['Nabisco' 'Quaker Oats' 'Kellogs' 'Ralston Purina' 'General Mills' 'Post'
 'AM Home Food']   ,   7

#### Reference: https://plotly.com/python-api-reference/generated/plotly.express.scatter

In [17]:
fig = px.scatter(df,
                x='sugars',
                y='rating',
                color = 'sodium',
                size = 'calories',
                symbol = 'type',
                hover_data=['fat','protein'],
                hover_name= df['name'].astype(str)+" : "+df['mfr'].astype(str),
                width = 800,
                title='Cereal ratings VS Sugars')
fig.show()

In [6]:
fig = px.scatter_3d(df, x='sugars', y='fat', z='rating', color='mfr')
fig.show()

## Find error data

In [7]:
rows_with_negative_one = df[df.eq(-1).any(axis=1)]
rows_with_negative_one

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating,cereal
4,Almond Delight,Ralston Purina,Cold,110,2,2,200,1.0,14.0,8,-1,25,Top,1.0,0.75,34.38,1
20,Cream of Wheat (Quick),Nabisco,Hot,100,3,0,80,1.0,21.0,0,-1,0,Middle,1.0,1.00,64.53,1
57,Quaker Oatmeal,Quaker Oats,Hot,100,5,2,0,2.7,-1.0,-1,110,0,Bottom,1.0,0.67,50.83,1

#Need to fix Quaker Oatmeal error. How?
============= End of the basic charts ===========================

In [8]:
fig = px.box(df,
                x='sugars',
                y='rating',
                hover_name='name',
                title='Cereal ratings vs. sugars')
                #points="all") #default is the outlier
fig.show()

### Ref: https://plotly.com/python-api-reference/generated/plotly.express.histogram.html

In [9]:
df['fat'].describe()

count    77.000000
mean      1.012987
std       1.006473
min       0.000000
25%       0.000000
50%       1.000000
75%       2.000000
max       5.000000
Name: fat, dtype: float64

In [10]:
fig = px.histogram(df, x='fat', title='Rating distribution', nbins=7) #,cumulative=True)
fig.show()

## Exercise 1: Plot 2D histogram of the cereal dataset.
### ref: https://plotly.com/python/2D-Histogram/

In [11]:
fig = px.scatter(df,
                x='sugars',
                y='rating',
                color='mfr',
                size='calories',
                facet_row='shelf',
                facet_col='type',
                facet_col_spacing=0.02,
                facet_row_spacing=0.05,
                hover_data=['fat','protein'],
                hover_name='name',
                category_orders={'shelf': ['Top', 'Middle', 'Bottom'],'type':['Hot','Cold']},
                 template='ggplot2',
                 title="Facet Chart")

fig.update_layout(
    title=dict(font=dict(size=40))
)

fig.show()

In [12]:
#fig = px.treemap(df, path=['mfr', 'shelf','calories','name'], values='cereal', title='Cereals by shelf location')   #title is information
fig = px.treemap(df, path=['mfr','shelf','name','sugars'],values='cereal', title='Cereals by shelf location',template='ggplot2')   #title is information
fig.show()
#values of each node.

In [13]:
df[df['mfr']=='Nabisco']

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating,cereal
0,100% Bran,Nabisco,Cold,70,4,1,130,10.0,5.0,6,280,25,Top,1.00,0.33,68.40,1
20,Cream of Wheat (Quick),Nabisco,Hot,100,3,0,80,1.0,21.0,0,-1,0,Middle,1.00,1.00,64.53,1
63,Shredded Wheat,Nabisco,Cold,80,2,0,0,3.0,16.0,0,95,0,Bottom,0.83,1.00,68.24,1
64,Shredded Wheat 'n'Bran,Nabisco,Cold,90,3,0,0,4.0,19.0,0,140,0,Bottom,1.00,0.67,74.47,1
65,Shredded Wheat spoon size,Nabisco,Cold,90,3,0,0,3.0,20.0,0,120,0,Bottom,1.00,0.67,72.80,1
68,Strawberry Fruit Wheats,Nabisco,Cold,90,2,0,15,3.0,15.0,5,90,25,Middle,1.00,1.00,59.36,1

In [14]:
fig = px.sunburst(df, path=['mfr','shelf','name','sugars'], values='cereal',template='ggplot2',title='Sun burst chart.')
fig.show()

## Exercise 2: Based on Chipotle dataset, set 2~3 questions and then plot charts using plotly express.

https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv

## DuckDB https://duckdb.org/docs/stable/clients/python/overview

In [15]:
#!pip install duckdb

In [16]:
import duckdb
x = duckdb.sql("select * from df where fat>2 or sugars>1").df()
x

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating,cereal
0,100% Bran,Nabisco,Cold,70,4,1,130,10.0,5.0,6,280,25,Top,1.0,0.33,68.40,1
1,100% Natural Bran,Quaker Oats,Cold,120,3,5,15,2.0,8.0,8,135,0,Top,1.0,1.00,33.98,1
2,All-Bran,Kellogs,Cold,70,4,1,260,9.0,7.0,5,320,25,Top,1.0,0.33,59.43,1
3,Almond Delight,Ralston Purina,Cold,110,2,2,200,1.0,14.0,8,-1,25,Top,1.0,0.75,34.38,1
4,Apple Cinnamon Cheerios,General Mills,Cold,110,2,2,180,1.5,10.5,10,70,25,Bottom,1.0,0.75,29.51,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,Triples,General Mills,Cold,110,2,1,250,0.0,21.0,3,60,25,Top,1.0,0.75,39.11,1
64,Trix,General Mills,Cold,110,1,1,140,0.0,13.0,12,25,25,Middle,1.0,1.00,27.75,1
65,Wheat Chex,Ralston Purina,Cold,100,3,1,230,3.0,17.0,3,115,25,Bottom,1.0,0.67,49.79,1
66,Wheaties,General Mills,Cold,100,3,1,200,3.0,17.0,3,110,25,Bottom,1.0,1.00,51.59,1
67,Wheaties Honey Gold,General Mills,Cold,110,2,1,200,1.0,16.0,8,60,25,Bottom,1.0,0.75,36.19,1

In [18]:
x.head

<bound method NDFrame.head of                        name             mfr  type  calories  protein  fat  \
0                 100% Bran         Nabisco  Cold        70        4    1
1         100% Natural Bran     Quaker Oats  Cold       120        3    5
2                  All-Bran         Kellogs  Cold        70        4    1
3            Almond Delight  Ralston Purina  Cold       110        2    2
4   Apple Cinnamon Cheerios   General Mills  Cold       110        2    2
..                      ...             ...   ...       ...      ...  ...
63                  Triples   General Mills  Cold       110        2    1
64                     Trix   General Mills  Cold       110        1    1
65               Wheat Chex  Ralston Purina  Cold       100        3    1
66                 Wheaties   General Mills  Cold       100        3    1
67      Wheaties Honey Gold   General Mills  Cold       110        2    1

    sodium  fiber  carbo  sugars  potass  vitamins   shelf  weight  cups  \
0      130   10.0    5.0       6     280        25     Top     1.0  0.33
1       15    2.0    8.0       8     135         0     Top     1.0  1.00
2      260    9.0    7.0       5     320        25     Top     1.0  0.33
3      200    1.0   14.0       8      -1        25     Top     1.0  0.75
4      180    1.5   10.5      10      70        25  Bottom     1.0  0.75
..     ...    ...    ...     ...     ...       ...     ...     ...   ...
63     250    0.0   21.0       3      60        25     Top     1.0  0.75
64     140    0.0   13.0      12      25        25  Middle     1.0  1.00
65     230    3.0   17.0       3     115        25  Bottom     1.0  0.67
66     200    3.0   17.0       3     110        25  Bottom     1.0  1.00
67     200    1.0   16.0       8      60        25  Bottom     1.0  0.75

    rating  cereal
0    68.40       1
1    33.98       1
2    59.43       1
3    34.38       1
4    29.51       1
..     ...     ...
63   39.11       1
64   27.75       1
65   49.79       1
66   51.59       1
67   36.19       1

[68 rows x 17 columns]>

In [19]:
x

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating,cereal
0,100% Bran,Nabisco,Cold,70,4,1,130,10.0,5.0,6,280,25,Top,1.0,0.33,68.40,1
1,100% Natural Bran,Quaker Oats,Cold,120,3,5,15,2.0,8.0,8,135,0,Top,1.0,1.00,33.98,1
2,All-Bran,Kellogs,Cold,70,4,1,260,9.0,7.0,5,320,25,Top,1.0,0.33,59.43,1
3,Almond Delight,Ralston Purina,Cold,110,2,2,200,1.0,14.0,8,-1,25,Top,1.0,0.75,34.38,1
4,Apple Cinnamon Cheerios,General Mills,Cold,110,2,2,180,1.5,10.5,10,70,25,Bottom,1.0,0.75,29.51,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,Triples,General Mills,Cold,110,2,1,250,0.0,21.0,3,60,25,Top,1.0,0.75,39.11,1
64,Trix,General Mills,Cold,110,1,1,140,0.0,13.0,12,25,25,Middle,1.0,1.00,27.75,1
65,Wheat Chex,Ralston Purina,Cold,100,3,1,230,3.0,17.0,3,115,25,Bottom,1.0,0.67,49.79,1
66,Wheaties,General Mills,Cold,100,3,1,200,3.0,17.0,3,110,25,Bottom,1.0,1.00,51.59,1
67,Wheaties Honey Gold,General Mills,Cold,110,2,1,200,1.0,16.0,8,60,25,Bottom,1.0,0.75,36.19,1

In [20]:
x.head(10)

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating,cereal
0,100% Bran,Nabisco,Cold,70,4,1,130,10.0,5.0,6,280,25,Top,1.00,0.33,68.40,1
1,100% Natural Bran,Quaker Oats,Cold,120,3,5,15,2.0,8.0,8,135,0,Top,1.00,1.00,33.98,1
2,All-Bran,Kellogs,Cold,70,4,1,260,9.0,7.0,5,320,25,Top,1.00,0.33,59.43,1
3,Almond Delight,Ralston Purina,Cold,110,2,2,200,1.0,14.0,8,-1,25,Top,1.00,0.75,34.38,1
4,Apple Cinnamon Cheerios,General Mills,Cold,110,2,2,180,1.5,10.5,10,70,25,Bottom,1.00,0.75,29.51,1
5,Apple Jacks,Kellogs,Cold,110,2,0,125,1.0,11.0,14,30,25,Middle,1.00,1.00,33.17,1
6,Basic 4,General Mills,Cold,130,3,2,210,2.0,18.0,8,100,25,Top,1.33,0.75,37.04,1
7,Bran Chex,Ralston Purina,Cold,90,2,1,200,4.0,15.0,6,125,25,Bottom,1.00,0.67,49.12,1
8,Bran Flakes,Post,Cold,90,3,0,210,5.0,13.0,5,190,25,Top,1.00,0.67,53.31,1
9,Cap'n'Crunch,Quaker Oats,Cold,120,1,2,220,0.0,12.0,12,35,25,Middle,1.00,0.75,18.04,1

In [21]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', delimiter='\t')

In [23]:
df.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [24]:
# แปลงราคาจาก string เป็น float
df['item_price'] = df['item_price'].str.replace('$', '', regex=False).astype(float)

In [25]:
import plotly.express as px

# รวมจำนวนชิ้นตามชื่อเมนู
top_items = df.groupby('item_name')['quantity'].sum().reset_index()
top_items = top_items.sort_values(by='quantity', ascending=False).head(5)

# สร้างกราฟแท่ง
fig1 = px.bar(top_items, x='item_name', y='quantity',
             title='Top 5 Most Popular Items (by Quantity)',
             color='quantity',
             text_auto=True)
fig1.show()

In [26]:
# คำนวณยอดรวมต่อ 1 order_id
order_total = df.groupby('order_id')['item_price'].sum().reset_index()

# สร้างกราฟ Histogram
fig2 = px.histogram(order_total, x='item_price',
                   nbins=30,
                   title='Distribution of Order Totals',
                   labels={'item_price': 'Order Total ($)'},
                   color_discrete_sequence=['indianred'])
fig2.show()

In [27]:
# สร้างคอลัมน์ใหม่เพื่อเช็คว่าเป็นเมนูไก่หรือไม่
df['is_chicken'] = df['item_name'].apply(lambda x: 'Chicken' if 'Chicken' in x else 'Other')

# รวมยอดขาย
chicken_vs_others = df.groupby('is_chicken')['item_price'].sum().reset_index()

# สร้างกราฟวงกลม
fig3 = px.pie(chicken_vs_others, values='item_price', names='is_chicken',
             title='Revenue Proportion: Chicken Items vs Others',
             hole=0.4, # ทำเป็นกราฟ Donut
             color_discrete_map={'Chicken':'#f39c12', 'Other':'#bdc3c7'})
fig3.show()

In [28]:
import plotly.express as px

# 1. รันโค้ด Clean ข้อมูลราคาก่อน (ถ้ายังไม่ได้ทำ)
# df['item_price'] = df['item_price'].str.replace('$', '', regex=False).astype(float)

# 2. สร้าง 2D Histogram / Density Heatmap
# แกน X: ราคา, แกน Y: จำนวน
fig = px.density_heatmap(df,
                        x='item_price',
                        y='quantity',
                        nbinsx=20, # จำนวนถัง (Bin) ของแกน X
                        nbinsy=10, # จำนวนถัง (Bin) ของแกน Y
                        title='2D Histogram: Order Quantity vs Item Price Density',
                        labels={'item_price': 'Item Price ($)', 'quantity': 'Quantity ordered'},
                        color_continuous_scale='Viridis', # สีไล่ระดับ
                        text_auto=True # แสดงตัวเลขจำนวนข้อมูลในช่อง
                       )

# ปรับปรุง layout เพื่อให้เห็นช่องสีเหลี่ยมชัดเจนขึ้น
fig.update_layout(
    xaxis=dict(ticks="outside"),
    yaxis=dict(ticks="outside")
)

fig.show()